name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-godemo-${{ github.run_id }}-${{ github.run_attempt }}
      - image:linux-5.0
      - instance-size:small
    steps:
      - name: test shell echo
        run: ls
      # - name: Build the Docker image
      #   run: docker build -t my-image-name:$(date +%s) ../../
